version: '3.8'
services:
  zabbix-proxy:
    container_name: "zbx-proxy"
    image: zabbix/zabbix-proxy-sqlite3:7.2.4-alpine
    user: root
    environment:
      - ZBX_PROXYMODE=0  # 0 - active proxy and 1 - passive proxy
      - ZBX_SERVER_HOST= 192.168.1.101    # IP OU DNS DO SEU ZABBIX SERVER
      - ZBX_SERVER_PORT=10051
      - ZBX_HOSTNAME=px-proxy-stack
      - ZBX_DEBUGLEVEL=3  # 0 - basic info, 1 - critical, 2 - error, 3 - warnings, 4 - for debugging, 5 - extended debugging
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_PROXYLOCALBUFFER=0  # mantém cópia dos eventos mesmo depois de enviar ao server (valor em horas)
      - ZBX_PROXYOFFLINEBUFFER=1  # 6 horas
      - ZBX_PROXYHEARTBEATFREQUENCY=60  # 60 seg
      - ZBX_CONFIGFREQUENCY=300  # 300 Seg
      - ZBX_DATASENDERFREQUENCY=1  # 1 Seg
      - ZBX_STARTHISTORYPOLLERS=3  # ----------------
      - ZBX_STARTPOLLERS=5 #500 
      - ZBX_STARTPREPROCESSORS=5 #500
      - ZBX_STARTPOLLERSUNREACHABLE=30   #300
      - ZBX_STARTPINGERS=5  #100
      - ZBX_STARTDISCOVERERS=3
      - ZBX_STARTHTTPPOLLERS=5
      - ZBX_HOUSEKEEPINGFREQUENCY=1
      - ZBX_STARTVMWARECOLLECTORS=1
      - ZBX_CACHESIZE=128M
      - ZBX_STARTDBSYNCERS=20 #20
      - ZBX_HISTORYCACHESIZE=256M
      - ZBX_HISTORYINDEXCACHESIZE=256M
      - ZBX_TIMEOUT=30  # 30 Seg
      - ZBX_UNREACHABLEPERIOD=400
      - ZBX_UNAVAILABLEDELAY=400
      - ZBX_UNREACHABLEDELAY=400
      - ZBX_LOGSLOWQUERIES=3000
      - ZBX_STATSALLOWEDIP=127.0.0.1
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"
    
    networks:
     - zabbix7
    restart: always
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts    
       - /zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
       - /zabbix-proxy/var/lib/zabbix/enc:/var/lib/zabbix/enc
       - /zabbix-proxy/var/lib/zabbix/mibs:/var/lib/zabbix/mibs

networks:
  zabbix7:
   driver: bridge